updated pipeline code, chart deployed in test cluster

diff --git a/pipeline.yml b/pipeline.yml
--- a/pipeline.yml
+++ b/pipeline.yml
@@ -1,48 +1,73 @@
+cluster_defaults: &cluster_defaults
+    stable_repo: "https://charts.helm.sh/stable"
+    cluster_ca: ((kubernetes.cluster_ca))
+    admin_cert: ((kubernetes.admin_cert))
+    admin_key: ((kubernetes.admin_key)) #
+    helm_history_max: 20
+
 resource_types:
   - name: helm
     type: docker-image
     source:
-      repository: alpine/helm
-      tag: "3.5.2"
-  - name: k8s
-    type: docker-image
-    source:
-      repository: pelotech/k8s-resource
-      tag: "v0.9.0"k
-
+        repository: typositoire/concourse-helm3-resource
+        tag: v1.16.0
+  
 resources:
-  - name: event-stats-chart
+  - name: git-repo
     type: git
     source:
       uri: "https://github.com/harshvirani7/event-stats-test.git"
-      branch: main
-  - name: k8s-cluster
-    type: k8s
+      branch: feature-es
+  - name: test
+    type: helm
     source:
-      kubeconfig: ((kubeconfig))
+        cluster_url: https://cluster.test.eencloud.com:6443
+        <<: *cluster_defaults
 
 jobs:
-  - name: deploy-helm-chart // deploy event stats
+  - name: build
     plan:
-      - get: event-stats-chart
+      - get: git-repo
         trigger: true
-      - get: k8s-cluster
-        trigger: true
-      - task: deploy-helm
+      - task: list-git-repo-contents
         config:
           platform: linux
           image_resource:
             type: docker-image
             source:
-              repository: alpine/helm
-              tag: "3.5.2"
+              repository: busybox
           inputs:
-            - name: event-stats-chart
+            - name: git-repo
           run:
             path: sh
             args:
               - -exc
               - |
-                export KUBECONFIG=k8s-cluster/kubeconfig/config
-                helm repo add stable https://charts.helm.sh/stable
-                helm upgrade --install event-stats-chart event-stats-chart/event-stats-chart-0.1.0.tgz --namespace default
+                echo "Listing contents of git-repo directory:"
+                ls -la git-repo
+      - task: check-directory
+        config:
+          platform: linux
+          image_resource:
+            type: docker-image
+            source:
+              repository: busybox
+          inputs:
+            - name: git-repo
+          run:
+            path: sh
+            args:
+              - -exc
+              - |
+                echo "Listing contents of git-repo:"
+                ls -la git-repo
+                echo "Checking if event-stats-chart exists:"
+                if [ -d "git-repo/event-stats-chart" ]; then
+                  echo "event-stats-chart directory found."
+                else
+                  echo "event-stats-chart directory not found."
+                  exit 1
+                fi
+      - put: test
+        params:
+          chart: git-repo/event-stats-chart  
